version: 2.1
executors:
  ruby19:
    docker:
      - image: ruby:1.9.3
jobs:
  test-on-ruby19:
    executor: ruby19
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec
workflows:
  version: 2.1
  test-with-many-versions:
    jobs:
      - test-on-ruby19
